### PR TITLE
Improved build flow and also added support of webpack/browserify

### PR DESCRIPTION
**Pull request by mdreizin**
Currently this PR helps to improved build flow:

- added `@@VERSION` macro;
- removed unesesary logic (wrap with closure);

Also it solves an issue when you need to use library on different environments [UMD](https://github.com/umdjs/umd).

I have added support to different environments `eve` and you need to review [this PR](https://github.com/adobe-webplatform/eve/pull/25) before.

### CODE REVIEW

**Comment by danielr-minted** [comment]
What is the status of this PR?  raphael is unusable in node and webpack without this PR and thus impossible to integrate into many compile/test/build flows.

**Comment by tomasAlabes** [comment]
I will take a look at it in a couple of weeks, I'm abroad right now.

**Comment by rafaelmaiolla** [comment]
I'm also using webpack, any news about when this will be merged? :)

**Comment by meta-meta** [comment]
Webpack user here. Raphael 2.1.4 and seeing essentially a duplicate of this issue:  ember-cli Cannot read property 'on' of undefined #918 

Looking forward to seeing this PR merged!

**Comment by tomasAlabes** [comment]
Guys could you check that it works in this branch? https://github.com/DmitryBaranovskiy/raphael/tree/mdreizin-master
Thanks!
(I want to know if everything works with this PR)

**Comment by meta-meta** [comment]
I just checked out e361cc429 and it resolves the issue I was seeing. Thanks for the quick attention!

**Comment by wurmr** [comment]
I'm still seeing the same error with webpack and that branch.

**Comment by tomasAlabes** [comment]
Any env with raphael + webpack that someone can lend/send me to reproduce this?

**Pull request merged**
