### PR TITLE
replace getElementById with querySelector to pierce through shadow DOM

### PR DESCRIPTION
**Pull request by wburgers**
The querySelector is more powerful than the getElementById selector.
QuerySelector can pierce through shadow DOM with the /deep/ combinator.

Hope this helps somebody.

### CODE REVIEW

**Comment by tomasAlabes** [comment]
Cannot merge it as it is not supported in IE7. Thanks anyway, stays as reference to other people needing this.

**Comment by wburgers** [comment]
http://www.theie7countdown.com/
IE7 is at less than 1% use worldwide.
Don't you think it is time to drop support for IE7?

Glad to see this project is active again ;-)
It is a great library.

**Comment by tomasAlabes** [comment]
The other thing that troubled me was this: http://jsperf.com/getelementbyid-vs-queryselector/129.
There is a x4 perf difference between the 2. I think we need more info on real world cases to see if this affects the perf of the library.

I'm the only contributor with Dmitry and the project runs in a lot of browsers/OS/devices, I need the help from people like you :)

**Comment by wburgers** [comment]
Now that is a concern I can get :-).
I just checked and the function getElementById is only called 8 times.
For most things the library keeps the main elements it needs in memory.
I don't think this change will affect the perf of the library that much, but I agree that more real world cases would be good.
Maybe find a project that heavily relies on raphael?

**Pull request closed without merging**
