### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by ferambot**
Hi, I am Feram 🤖

I'm a bot and I work on behalf of [adius][adius].
If my merge request helped to improve this repository,
feel free to [star my repo][feram] to show some love! 😊

If I didn't behave, you can [create an issue][issues]
and my Dad will try to fix me.

Love, hugs and kisses,
your [Feram][https://github.com/ferambot]

[adius]: https://github.com/adius
[feram]:
[issues]: https://github.com/adius/feram/issues

### CODE REVIEW

**Comment by tomasAlabes** [comment]
Hello Feram, I appreciate your PR, but I see you changed a method's name as a typo and, although the change is correct, I prefer not to break people's code by changing the method's name.

**Comment by adius** [comment]
Well I guess the correct way would be to fix it,
create an alias of the version with the typo to the correct one
and print a deprecated warning if somebody uses the version with the typo
…and then someday the wrong version can be removed

Would you accept an pull request for this?

**Comment by tomasAlabes** [comment]
Hi @adius, not sure what you mean, but I have already fixed them with 8f74e73. 
Thanks for the interest anyway :)

**Comment by adius** [comment]
I'm talking about fixing the .fullfill method which should be .fulfill

**Comment by adius** [comment]
Oh and btw, It's considered rude to merge someone else's commits, without keeping them as the author. Feram would have deserved some credit…

**Comment by tomasAlabes** [comment]
Ok, now I get the comment, yeah, I think it's a very small issue but that could be a way to fix it.
I gave feram the opportunity to change his PR...and I don't think he has feelings, at least not yet 😮
I'll add him to the history.md...

**Comment by adius** [comment]
You could have simply `git cherry-pick` the commits you wanted
and everything would have been as it's supposed to...
Anyways … maybe next time 😉

**Pull request closed without merging**
