### PR TITLE
Fix for gradient fills

### PR DESCRIPTION
**Pull request by ericliao**
Fixes DmitryBaranovskiy/raphael/issues/933

Broken
http://ericliao.github.io/raphael/picker-2.1.3.html

Fixed:
http://ericliao.github.io/raphael/picker-2.1.3-patched.html

### CODE REVIEW

**Comment by qurben** [comment]
I don't know why the url of the page was put in front of these references. There might be a usecase. A better fix for this would be to use `document.location.origin + document.location.pathname` instead of `document.location` and instead of nothing at all.

**Comment by tomasAlabes** [comment]
#781 and 57b62b1b2f7d403b6046cd00603686b621562018 try to fix this. Could you confirm it?

**Comment by sergdenisov** [comment]
@tomasAlabes why closed? I can confirm that https://github.com/DmitryBaranovskiy/raphael/issues/781 and https://github.com/DmitryBaranovskiy/raphael/commit/57b62b1b2f7d403b6046cd00603686b621562018 didn't fix this bug for IE9. But this fix do it:

screen shot 2015-05-29 at 19 11 03
screen shot 2015-05-29 at 19 11 05

**Comment by tomasAlabes** [comment]
Now?

**Comment by sergdenisov** [comment]
@tomasAlabes black anyway(.

**Comment by marceloxp** [comment]
https://github.com/DmitryBaranovskiy/raphael/issues/990 To fix black gradient:

**Pull request closed without merging**
